<?php 
// Enter your full name here. This will also be used to search for what other people are saying about you, so you probably should go with your professional name.
$fullname = "Nat Welch";

// This is a paragraph sized description of you that appears at the top of the page.
$description = "Leo is a PhD student in the Tangible Media Group at the Media Lab. He has a background in sculpture, architecture and industrial design as well as an MS from the Media Lab spent working on the kitchen of the future. He is interested in augmenting our interaction with the physical environment through innovative HCI, product and material design.";

// Leave this blank if you don't want to publish your email address.
$email = "nat@natwelch.com";

// Ignore this for now
$usetwitter = false;

// If you'd like more articles to appear you can change this number. Also if you want less.
$zeitlength = 10;

// Enter the rss/atom/etc. feeds of any blogs you have as below (seperated by commas and enclosed in single quotes).
//$blogfeeds = array('http://hyperexperience.com/?feed=rss2', 'http://leo.media.mit.edu/?feed=rss2', 'http://possessedproducts.com/?feed=rss2');
$blogfeeds = array('http://pseudoweb.net/feed');

// Enter the names for the blogs above (in order and seperated by commas and enclosed in single quotes).
//$blognames = array('Hyperexperience', 'Leo at the Media Lab', 'Possessed Products');
$blognames = array('PseudoWeb.Net');

// Enter the rss/atom/etc. feeds of any bookmark feeds (del.icio.us, google reader starred, etc.) you have as below (seperated by commas and enclosed in single quotes).
$bookmarkfeeds = array('http://www.google.com/reader/public/atom/user/03039824401098534155/state/com.google/broadcast','http://del.icio.us/rss/calvin166');

// Enter the feed of your flickr public photos.
$imagefeedurl = "http://api.flickr.com/services/feeds/photos_public.gne?id=42027916@N00&amp;lang=en-us&format=atom";
?>